name: Build Master

on:
  push:
    branches: [ master ]

jobs:
    build:
      runs-on: windows-latest
      steps:
        - name: Get the sources
          uses: actions/checkout@v1
        - name: Run the build script
          uses: cake-build/cake-action@v1.1.1
