name: Build Master

on:
  push:
    branches: [ master, develop ]

jobs:
    build:
      runs-on: windows-latest
      steps:
        - name: Get the sources
          uses: actions/checkout@v1
        - name: .NetFramework Action Template
          uses: auycro/netframework-action-template@v0.0.2  
        - name: Setup Nuget.exe
          uses: warrenbuckley/Setup-Nuget@v1        
        - name: Run the build script
          uses: cake-build/cake-action@v1.1.1
